// Code generated by miqt-rcc; DO NOT EDIT.
package ui

import (
	"embed"

	qt "github.com/mappu/miqt/qt6"
)

//go:embed resources.rcc
var _resourceRcc []byte

func init() {
	_ = embed.FS{}
	qt.QResource_RegisterResourceWithRccData(&_resourceRcc[0])
}
